### ISSUE TITLE
Feature Request: Show OSD when seeking

### ISSUE THREAD

**Issue by RafeeDaBoy** [Raventhicc/MPV-Morden-X#1]
When seeking, the default mpv seekbar pops up. It would be nice if the ModernX OSD controls would show when seeking

**Comment by Raventhicc** [comment]
I'm not the author of the OSD script (or any of them used here, I have linked everything I've used in the readme.md). I just compiled the one's I like. The OSD I'm using is [cyl0's mordex-x](https://github.com/cyl0/mpv-osc-morden-x), so you should request feature on that repo.
